### PR TITLE
Fixing Tetris Score Issue

### PR DESCRIPTION
**Pull request by Heroshane1**
During the move of Tetris' JS to the JS folder, some of the features added were dropped, including score. This reintroduces scoring. Modifications done to tetris.js

### CODE REVIEW

**Comment by Dylemperor** [comment]
It looks as if you removed the quick-drop and scroll-stopping features when fixing the score

**Comment by Heroshane1** [comment]
Having issues with VS. When I try to merge dev into RCTetrisScore after pulling changes from dev, it won't keep dev's changes.

**Comment by chrisseals98** [comment]
> Having issues with VS. When I try to merge dev into RCTetrisScore after pulling changes from dev, it won't keep dev's changes.

What's going on with it?

**Comment by Heroshane1** [comment]
Due to VS errors, I will be closing this PR so that it doesn't accidentally get merged in.

**Pull request closed without merging**
