### PR TITLE
Update Tetris.cshtml

### PR DESCRIPTION
**Pull request by djjones95**
Added description to Tetris

### CODE REVIEW

**Review by Heroshane1 — CHANGES_REQUESTED** [review]
Maybe there should be a small sentence or two explaining the controls?

**Review by Heroshane1 — APPROVED** [review]
Adding instructions for the controls would be nice, but it's good for now.

**Comment by Dylemperor** [comment]
Good description, controls explanation would be good as the others said

**Review by Dylemperor — APPROVED** [review]
Good

**Pull request merged**
